### ISSUE TITLE
solve cache PR #244

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#259]
refer to PR

**Comment by P-Miranda** [comment]
you can add link to issues in other repositories like this
iobundle/iob-cache#244

**Comment by jjts** [comment]
thanks 

issues and PRs!

**Comment by P-Miranda** [comment]
- the objective of the referenced cache PR was to work with the latest LIB version and fix issue #201 
- the comments regarding automation of swreg files require further analysis
- If I recall correctly the swreg file generation was on LIB/setup.mk previously, but that turned out to be a problem for cases where we want to generate the swreg files for subcores ( for example generate iob_cache_swreg_def.vh or iob_uart_swreg_def.vh for iob-soc core)
- my advice would be to leave this issue until we have a working version for iob-soc build-lib

**Comment by jjts** [comment]
Agreed

**Comment by jjts** [comment]
in progress

**Comment by jjts** [comment]
This issue is deprecated as setup is now python based
